name: Central DevSecOps Pipeline

on:
  workflow_call:

jobs:
  security-scans:
    name: Enterprise Security Scans
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Semgrep
        run: |
          pip install semgrep

      - name: Run SAST Scan
        run: |
          semgrep scan --config auto . || true
